name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to v3 which is compatible with Node.js 20

      - name: Generate the Snake
        uses: Platane/snk@v2.1.0 # Updated to the latest stable version
        id: snake-gif
        with:
          github_user_name: l3hautikpatel
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show Git Status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@v3 # Updated to the latest version compatible with Node.js 20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3 # Updated to the latest version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
